[tool.poetry]
name = "maison"
version = "1.4.0"
description = "Maison"
authors = ["Dom Batten <dominic.batten@googlemail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/dbatten5/maison"
repository = "https://github.com/dbatten5/maison"
documentation = "https://dbatten5.github.io/maison"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

[tool.poetry.urls]
Changelog = "https://github.com/dbatten5/maison/releases"

[tool.poetry.dependencies]
python = "^3.7.1"
click = "^8.0.1"
pydantic = "^1.10.4"
toml = "^0.10.2"

[tool.poetry.group.test.dependencies]
pytest = "^6.2.4"
coverage = {extras = ["toml"], version = "^6.1"}

[tool.poetry.group.dev.dependencies]
xdoctest = {extras = ["colors"], version = "^0.15.5"}
typeguard = "^2.13.2"
safety = "^2.2.0"
mypy = "^0.910"
pre-commit = "^2.16.0"
flake8 = "^4.0.1"
black = "^20.8b1"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^21.11.29"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.3"
pep8-naming = "^0.12.0"
darglint = "^1.8.0"
reorder-python-imports = "^2.6.0"
pre-commit-hooks = "^4.0.1"
Pygments = "^2.9.0"

[tool.poetry.scripts]
maison = "maison.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["maison"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[tool.mypy]
strict = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[[tool.mypy.overrides]]
module = ["toml"]
ignore_missing_imports = true

[tool.isort]
profile = "open_stack"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
